sequenceDiagram
    participant D as 医生
    participant F as 注册窗口
    participant B as 后台管理系统
    participant DB as 数据库存储系统
    D->>F: 查看待检任务
    activate F
    F->>B: 查询任务列表
    activate B
    B->>DB: 查询任务项
    activate DB
    DB-->>B: 返回列表
    deactivate DB
    B-->>F: 返回数据
    deactivate B
    F-->>D: 显示待检任务
    deactivate F
    D->>F: 开始检查
    activate F
    F->>B: 更新状态
    activate B
    B->>DB: 待检查转检查中
    activate DB
    DB-->>B: 成功
    deactivate DB
    B-->>F: 成功
    deactivate B
    F-->>D: 进入录入页面
    deactivate F
    D->>F: 录入检查结果
    activate F
    F->>B: 保存结果
    activate B
    B->>DB: 写入结果标记异常
    activate DB
    DB-->>B: 成功
    deactivate DB
    B-->>F: 成功
    deactivate B
    F-->>D: 录入成功
    deactivate F
    D->>F: 完成检查
    activate F
    F->>B: 更新状态
    activate B
    B->>DB: 检查中转已完成
    activate DB
    DB-->>B: 成功
    deactivate DB
    B-->>F: 成功
    deactivate B
    F-->>D: 检查完成
    deactivate F
    Note over D,DB: 生成报告
    D->>F: 生成报告
    activate F
    F->>B: 归集结果
    activate B
    B->>DB: 按模板生成
    activate DB
    DB-->>B: 成功
    deactivate DB
    B-->>F: 返回编号
    deactivate B
    F-->>D: 报告生成
    deactivate F
    D->>F: 审核发布
    activate F
    F->>B: 审核报告
    activate B
    B->>DB: 更新审核状态
    activate DB
    DB-->>B: 成功
    deactivate DB
    F->>B: 发布报告
    activate B
    B->>DB: 发布
    activate DB
    DB-->>B: 成功
    deactivate DB
    B-->>F: 成功
    deactivate B
    F-->>D: 报告已发布
    deactivate F
