export { useLoading } from './useLoading'
export { useStatusTag, appointmentStatusMap, orderStatusMap, examTaskStatusMap, examItemStatusMap, reportStatusMap, consultationStatusMap, refundStatusMap, abnormalLevelMap } from './useStatusTag'
export type { StatusMap, StatusMapItem, TagType } from './useStatusTag'
export { usePagination } from './usePagination'
export type { PaginationState, UsePaginationOptions } from './usePagination'
