DROP DATABASE IF EXISTS `xixin_health`;
CREATE DATABASE `xixin_health` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `xixin_health`;

CREATE TABLE `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_no` VARCHAR(32) NOT NULL COMMENT '用户编号',
  `name` VARCHAR(64) NOT NULL COMMENT '姓名',
  `gender` TINYINT NOT NULL DEFAULT 0 COMMENT '性别�?未知 1�?2�?,
  `birth_date` DATE DEFAULT NULL COMMENT '出生日期',
  `id_type` TINYINT DEFAULT NULL COMMENT '证件类型',
  `id_no` VARCHAR(64) DEFAULT NULL COMMENT '证件号码',
  `mobile` VARCHAR(20) NOT NULL COMMENT '手机�?,
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `password_hash` VARCHAR(128) DEFAULT NULL COMMENT '��¼�����ϣ',
  `address` VARCHAR(256) DEFAULT NULL COMMENT '地址',
  `emergency_contact` VARCHAR(64) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_mobile` VARCHAR(20) DEFAULT NULL COMMENT '紧急联系电�?,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `last_login_at` DATETIME(3) DEFAULT NULL COMMENT '最近登录时�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_no` (`user_no`),
  UNIQUE KEY `uk_mobile` (`mobile`),
  UNIQUE KEY `uk_id_no` (`id_no`),
  KEY `idx_name_mobile` (`name`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户�?;

CREATE TABLE `staff_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL COMMENT '��̨�˺�',
  `password_hash` VARCHAR(128) NOT NULL COMMENT '�����ϣ',
  `display_name` VARCHAR(64) NOT NULL COMMENT '��ʾ����',
  `bind_user_id` BIGINT NOT NULL COMMENT '���û�ID',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '״̬��1���� 0ͣ��',
  `last_login_at` DATETIME(3) DEFAULT NULL COMMENT '�����¼ʱ��',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_account_username` (`username`),
  KEY `idx_bind_user_id` (`bind_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='��̨�˺ű�';

CREATE TABLE `staff_role_rel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `staff_account_id` BIGINT NOT NULL COMMENT '��̨�˺�ID',
  `role_code` VARCHAR(32) NOT NULL COMMENT '��ɫ����',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_role` (`staff_account_id`,`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='��̨�˺Ž�ɫ������';

CREATE TABLE `health_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `allergy_history` TEXT COMMENT '过敏�?,
  `past_medical_history` TEXT COMMENT '既往病史',
  `family_history` TEXT COMMENT '家族病史',
  `medication_history` TEXT COMMENT '用药�?,
  `smoking_status` TINYINT NOT NULL DEFAULT 0 COMMENT '吸烟状�?,
  `drinking_status` TINYINT NOT NULL DEFAULT 0 COMMENT '饮酒状�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_profile` (`user_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='健康档案�?;

CREATE TABLE `exam_package` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `package_code` VARCHAR(32) NOT NULL COMMENT '套餐编码',
  `package_name` VARCHAR(128) NOT NULL COMMENT '套餐名称',
  `category` VARCHAR(32) DEFAULT NULL COMMENT '套餐分类',
  `price` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1上架 0下架',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_code` (`package_code`),
  KEY `idx_package_name` (`package_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检套餐�?;

CREATE TABLE `exam_package_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '检查项编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '检查项名称',
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '参考范�?,
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_item` (`package_id`,`item_code`),
  KEY `idx_package_id` (`package_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='套餐检查项�?;

CREATE TABLE `appointment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '预约单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `appoint_date` DATE NOT NULL COMMENT '预约日期',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '时段编码',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待确�?1已确�?2已完�?3已取�?4爽约',
  `cancel_reason` VARCHAR(256) DEFAULT NULL COMMENT '取消原因',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_appointment_no` (`appointment_no`),
  KEY `idx_user_date` (`user_id`,`appoint_date`),
  KEY `idx_center_date_slot` (`center_code`,`appoint_date`,`time_slot_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约�?;

CREATE TABLE `appointment_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `queue_no` VARCHAR(32) NOT NULL COMMENT '候补单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `appoint_date` DATE NOT NULL COMMENT '预约日期',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '时段编码',
  `priority` INT NOT NULL DEFAULT 0 COMMENT '优先�?,
  `queue_status` TINYINT NOT NULL DEFAULT 0 COMMENT '候补状态：0排队�?1已补�?2已失�?3已取�?,
  `expire_at` DATETIME(3) DEFAULT NULL COMMENT '过期时间',
  `confirmed_at` DATETIME(3) DEFAULT NULL COMMENT '确认时间',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_queue_no` (`queue_no`),
  KEY `idx_queue_user_date` (`user_id`,`appoint_date`),
  KEY `idx_queue_center_slot` (`center_code`,`appoint_date`,`time_slot_code`,`queue_status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ԤԼ�򲹱�';

CREATE TABLE `exam_center` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '���ı���',
  `center_name` VARCHAR(128) NOT NULL COMMENT '��������',
  `address` VARCHAR(256) DEFAULT NULL COMMENT '��ַ',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '��ϵ�绰',
  `business_hours` VARCHAR(128) DEFAULT NULL COMMENT 'Ӫҵʱ��',
  `description` TEXT DEFAULT NULL COMMENT '���Ľ���',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '״̬��1���� 0ͣ��',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_center_code` (`center_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='������ı�';

CREATE TABLE `resource_capacity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `appoint_date` DATE NOT NULL COMMENT '预约日期',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '时段编码',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '资源类型',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '资源编码',
  `capacity_total` INT NOT NULL DEFAULT 0 COMMENT '总容�?,
  `capacity_used` INT NOT NULL DEFAULT 0 COMMENT '已用容量',
  `capacity_locked` INT NOT NULL DEFAULT 0 COMMENT '锁定容量',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '״̬��1���� 0ͣ��',
  `version_no` INT NOT NULL DEFAULT 0 COMMENT '版本�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resource_capacity` (`center_code`,`appoint_date`,`time_slot_code`,`resource_type`,`resource_code`),
  KEY `idx_capacity_slot` (`center_code`,`appoint_date`,`time_slot_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源容量�?;

CREATE TABLE `resource_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `snapshot_no` VARCHAR(32) NOT NULL COMMENT '快照�?,
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '预约单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `appoint_date` DATE NOT NULL COMMENT '预约日期',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '时段编码',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '资源类型',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '资源编码',
  `version_no` INT NOT NULL DEFAULT 0 COMMENT '版本�?,
  `lock_result` TINYINT NOT NULL DEFAULT 0 COMMENT '锁定结果',
  `snapshot_data` TEXT COMMENT '快照数据',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_no` (`snapshot_no`),
  KEY `idx_snapshot_appointment` (`appointment_no`),
  KEY `idx_snapshot_slot` (`center_code`,`appoint_date`,`time_slot_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源快照�?;

CREATE TABLE `schedule_resource_bind` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '时段编码',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '检查项编码',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '资源类型',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '资源编码',
  `resource_name` VARCHAR(128) DEFAULT NULL COMMENT '资源名称',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_schedule_resource_bind` (`center_code`,`time_slot_code`,`package_id`,`item_code`,`resource_type`,`resource_code`),
  KEY `idx_bind_package` (`package_id`,`item_code`),
  KEY `idx_bind_resource` (`center_code`,`time_slot_code`,`resource_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='时段资源绑定�?;

CREATE TABLE `order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `appointment_id` BIGINT NOT NULL COMMENT '预约ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '总金�?,
  `pay_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待支�?1已支�?2已退�?3部分退�?4已完�?5已关�?,
  `pay_channel` VARCHAR(32) DEFAULT NULL COMMENT '支付渠道',
  `pay_time` DATETIME(3) DEFAULT NULL COMMENT '支付时间',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  UNIQUE KEY `uk_appointment_id` (`appointment_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单�?;

CREATE TABLE `order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `item_type` TINYINT NOT NULL DEFAULT 0 COMMENT '类型�?套餐�?1附加�?,
  `ref_item_code` VARCHAR(32) NOT NULL COMMENT '关联项编�?,
  `ref_item_name` VARCHAR(128) NOT NULL COMMENT '关联项名�?,
  `qty` INT NOT NULL DEFAULT 1 COMMENT '数量',
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '单价',
  `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '金额',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_ref_item` (`order_id`,`ref_item_code`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单明细�?;

CREATE TABLE `order_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `snapshot_type` VARCHAR(32) NOT NULL COMMENT '快照类型',
  `snapshot_content` TEXT NOT NULL COMMENT '快照内容',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order_snapshot` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单快照�?;

CREATE TABLE `order_settlement_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_item_id` BIGINT NOT NULL COMMENT '订单项ID',
  `settlement_type` VARCHAR(32) NOT NULL COMMENT '结算类型',
  `origin_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '原始金额',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '优惠分摊金额',
  `settlement_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '结算金额',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order_item` (`order_id`,`order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单结算明细�?;

CREATE TABLE `payment_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `payment_no` VARCHAR(32) NOT NULL COMMENT '支付流水�?,
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `channel` VARCHAR(32) NOT NULL COMMENT '支付渠道',
  `trade_no` VARCHAR(64) DEFAULT NULL COMMENT '第三方交易号',
  `pay_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '支付金额',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待支�?1成功 2失败',
  `pay_time` DATETIME(3) DEFAULT NULL COMMENT '支付时间',
  `callback_time` DATETIME(3) DEFAULT NULL COMMENT '回调时间',
  `raw_payload` TEXT COMMENT '原始回调数据',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_no` (`payment_no`),
  KEY `idx_payment_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付流水�?;

CREATE TABLE `refund_apply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apply_no` VARCHAR(32) NOT NULL COMMENT '退款申请单�?,
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `refund_type` VARCHAR(32) NOT NULL COMMENT '退款类�?,
  `apply_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '申请退款金�?,
  `reason` VARCHAR(256) DEFAULT NULL COMMENT '申请原因',
  `apply_status` TINYINT NOT NULL DEFAULT 0 COMMENT '申请状态：0待审�?1审核通过 2审核拒绝 3退款中 4已完�?,
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审核状�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_refund_apply_order` (`order_id`,`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款申请表';

CREATE TABLE `refund_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_apply_id` BIGINT NOT NULL COMMENT '退款申请ID',
  `apply_no` VARCHAR(32) NOT NULL COMMENT '退款申请单�?,
  `audit_action` VARCHAR(32) NOT NULL COMMENT '审核动作',
  `audit_result` VARCHAR(32) NOT NULL COMMENT '审核结果',
  `audit_remark` VARCHAR(512) DEFAULT NULL COMMENT '审核备注',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_refund_apply_id` (`refund_apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款审核日志表';

CREATE TABLE `refund_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_no` VARCHAR(32) NOT NULL COMMENT '退款流水号',
  `refund_apply_id` BIGINT NOT NULL COMMENT '退款申请ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `channel` VARCHAR(32) NOT NULL COMMENT '退款渠�?,
  `channel_refund_no` VARCHAR(64) DEFAULT NULL COMMENT '渠道退款单�?,
  `refund_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '退款金�?,
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0处理�?1成功 2失败',
  `refund_time` DATETIME(3) DEFAULT NULL COMMENT '退款时�?,
  `raw_payload` TEXT COMMENT '原始返回数据',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no` (`refund_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_refund_apply_id` (`refund_apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款执行结果表';

CREATE TABLE `exam_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(32) NOT NULL COMMENT '体检任务�?,
  `appointment_id` BIGINT NOT NULL COMMENT '预约ID',
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '预约单号',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单�?,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `task_date` DATE NOT NULL COMMENT '体检日期',
  `task_status` TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态：0待到�?1进行�?2已完�?3已取�?,
  `report_status` TINYINT NOT NULL DEFAULT 0 COMMENT '报告状态：0未生�?1生成�?2待审�?3已发�?,
  `guide_status` TINYINT NOT NULL DEFAULT 0 COMMENT '导检状态：0未开�?1进行�?2已完�?,
  `arrive_time` DATETIME(3) DEFAULT NULL COMMENT '到院时间',
  `start_time` DATETIME(3) DEFAULT NULL COMMENT '开始时�?,
  `complete_time` DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  UNIQUE KEY `uk_exam_task_appointment_id` (`appointment_id`),
  KEY `idx_exam_task_user_status` (`user_id`,`task_status`),
  KEY `idx_exam_task_center_date` (`center_code`,`task_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检任务�?;

CREATE TABLE `exam_department_route` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `route_code` VARCHAR(32) NOT NULL COMMENT '导检路线编码',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '检查项编码',
  `department_code` VARCHAR(32) NOT NULL COMMENT '科室编码',
  `department_name` VARCHAR(128) NOT NULL COMMENT '科室名称',
  `room_no` VARCHAR(64) DEFAULT NULL COMMENT '房间�?,
  `floor_no` VARCHAR(32) DEFAULT NULL COMMENT '楼层',
  `building_no` VARCHAR(32) DEFAULT NULL COMMENT '楼栋',
  `route_sort` INT NOT NULL DEFAULT 0 COMMENT '路线顺序',
  `guide_text` VARCHAR(512) DEFAULT NULL COMMENT '导检提示',
  `need_empty_stomach` TINYINT NOT NULL DEFAULT 0 COMMENT '是否空腹',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_code` (`route_code`),
  UNIQUE KEY `uk_route_package_item` (`center_code`,`package_id`,`item_code`),
  KEY `idx_route_center_package` (`center_code`,`package_id`,`route_sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导检路线�?;

CREATE TABLE `exam_task_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_item_no` VARCHAR(32) NOT NULL COMMENT '任务项号',
  `task_id` BIGINT NOT NULL COMMENT '任务ID',
  `task_no` VARCHAR(32) NOT NULL COMMENT '任务�?,
  `item_code` VARCHAR(32) NOT NULL COMMENT '检查项编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '检查项名称',
  `department_code` VARCHAR(32) NOT NULL COMMENT '科室编码',
  `department_name` VARCHAR(128) NOT NULL COMMENT '科室名称',
  `doctor_id` BIGINT DEFAULT NULL COMMENT '医生ID',
  `doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '医生姓名',
  `room_no` VARCHAR(64) DEFAULT NULL COMMENT '房间�?,
  `route_sort` INT NOT NULL DEFAULT 0 COMMENT '路线顺序',
  `item_status` TINYINT NOT NULL DEFAULT 0 COMMENT '项目状态：0待检�?1检查中 2已完�?3已跳�?4需复检',
  `entry_status` TINYINT NOT NULL DEFAULT 0 COMMENT '录入状态：0未录�?1已暂�?2已提�?,
  `start_time` DATETIME(3) DEFAULT NULL COMMENT '开始时�?,
  `complete_time` DATETIME(3) DEFAULT NULL COMMENT '完成时间',
  `skip_reason` VARCHAR(256) DEFAULT NULL COMMENT '跳过原因',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_item_no` (`task_item_no`),
  UNIQUE KEY `uk_task_item_unique` (`task_id`,`item_code`),
  KEY `idx_task_route` (`task_id`,`route_sort`),
  KEY `idx_doctor_status` (`doctor_id`,`item_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检任务项表';

CREATE TABLE `exam_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `result_no` VARCHAR(32) NOT NULL COMMENT '结果�?,
  `task_id` BIGINT NOT NULL COMMENT '任务ID',
  `task_item_id` BIGINT NOT NULL COMMENT '任务项ID',
  `task_item_no` VARCHAR(32) NOT NULL COMMENT '任务项号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `report_id` BIGINT DEFAULT NULL COMMENT '报告ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '检查项编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '检查项名称',
  `result_type` VARCHAR(32) NOT NULL COMMENT '结果类型',
  `result_value` VARCHAR(256) DEFAULT NULL COMMENT '结果文本�?,
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '结果数�?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '参考范�?,
  `conclusion` VARCHAR(512) DEFAULT NULL COMMENT '检查结�?,
  `is_abnormal` TINYINT NOT NULL DEFAULT 0 COMMENT '是否异常',
  `abnormal_level` TINYINT NOT NULL DEFAULT 0 COMMENT '异常级别',
  `entry_doctor_id` BIGINT DEFAULT NULL COMMENT '录入医生ID',
  `entry_doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '录入医生姓名',
  `entry_time` DATETIME(3) DEFAULT NULL COMMENT '录入时间',
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0未审�?1已复�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_result_no` (`result_no`),
  KEY `idx_result_task_item` (`task_item_id`),
  KEY `idx_result_user_item` (`user_id`,`item_code`),
  KEY `idx_result_report_id` (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检结果�?;

CREATE TABLE `exam_result_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `attachment_no` VARCHAR(32) NOT NULL COMMENT '附件�?,
  `result_id` BIGINT NOT NULL COMMENT '结果ID',
  `task_item_id` BIGINT NOT NULL COMMENT '任务项ID',
  `file_name` VARCHAR(256) NOT NULL COMMENT '文件�?,
  `file_url` VARCHAR(512) NOT NULL COMMENT '文件地址',
  `file_type` VARCHAR(64) DEFAULT NULL COMMENT '文件类型',
  `file_size` BIGINT DEFAULT NULL COMMENT '文件大小',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_attachment_no` (`attachment_no`),
  KEY `idx_result_id` (`result_id`),
  KEY `idx_task_item_id` (`task_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检结果附件�?;

CREATE TABLE `report_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `template_code` VARCHAR(32) NOT NULL COMMENT '模板编码',
  `template_name` VARCHAR(128) NOT NULL COMMENT '模板名称',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `template_type` VARCHAR(32) NOT NULL COMMENT '模板类型',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '版本�?,
  `render_engine` VARCHAR(32) DEFAULT NULL COMMENT '渲染引擎',
  `template_config` TEXT COMMENT '模板配置',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_code` (`template_code`),
  KEY `idx_package_status` (`package_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告模板�?;

CREATE TABLE `report_section_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `template_id` BIGINT NOT NULL COMMENT '模板ID',
  `section_code` VARCHAR(32) NOT NULL COMMENT '章节编码',
  `section_name` VARCHAR(128) NOT NULL COMMENT '章节名称',
  `section_type` VARCHAR(32) NOT NULL COMMENT '章节类型',
  `data_source_type` VARCHAR(32) NOT NULL COMMENT '数据来源类型',
  `item_codes` TEXT COMMENT '指标编码集合',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序�?,
  `render_rule` TEXT COMMENT '渲染规则',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_section` (`template_id`,`section_code`),
  KEY `idx_template_sort` (`template_id`,`sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告模板章节�?;

CREATE TABLE `exam_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_no` VARCHAR(32) NOT NULL COMMENT '报告编号',
  `appointment_id` BIGINT NOT NULL COMMENT '预约ID',
  `task_id` BIGINT NOT NULL COMMENT '体检任务ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `template_id` BIGINT DEFAULT NULL COMMENT '模板ID',
  `report_date` DATE NOT NULL COMMENT '报告日期',
  `overall_conclusion` TEXT COMMENT '总体结论',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0生成�?1待审�?2已审�?3已发�?4已撤�?,
  `pdf_url` VARCHAR(512) DEFAULT NULL COMMENT 'PDF地址',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '版本�?,
  `published_at` DATETIME(3) DEFAULT NULL COMMENT '发布时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`),
  UNIQUE KEY `uk_exam_report_appointment_id` (`appointment_id`),
  UNIQUE KEY `uk_exam_report_task_id` (`task_id`),
  KEY `idx_user_report_date` (`user_id`,`report_date`),
  KEY `idx_report_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检报告�?;

CREATE TABLE `exam_report_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_id` BIGINT NOT NULL COMMENT '报告ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '指标编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '指标名称',
  `result_value` VARCHAR(256) DEFAULT NULL COMMENT '结果�?,
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '结果数�?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '参考范�?,
  `is_abnormal` TINYINT NOT NULL DEFAULT 0 COMMENT '是否异常',
  `abnormal_level` TINYINT NOT NULL DEFAULT 0 COMMENT '异常级别',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_item` (`report_id`,`item_code`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_item_code` (`item_code`),
  KEY `idx_abnormal` (`is_abnormal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告指标�?;

CREATE TABLE `exam_report_item_abnormal` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_id` BIGINT NOT NULL COMMENT '报告ID',
  `report_item_id` BIGINT NOT NULL COMMENT '报告指标ID',
  `abnormal_code` VARCHAR(32) NOT NULL COMMENT '异常编码',
  `abnormal_name` VARCHAR(128) NOT NULL COMMENT '异常名称',
  `abnormal_level` TINYINT NOT NULL DEFAULT 1 COMMENT '异常级别',
  `suggestion` VARCHAR(512) DEFAULT NULL COMMENT '建议',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待跟�?1已跟�?2已忽�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_item_abnormal` (`report_item_id`,`abnormal_code`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_level_status` (`abnormal_level`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告异常项表';

CREATE TABLE `doctor_review_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_no` VARCHAR(32) NOT NULL COMMENT '审核流水�?,
  `report_id` BIGINT NOT NULL COMMENT '报告ID',
  `task_id` BIGINT NOT NULL COMMENT '体检任务ID',
  `review_stage` VARCHAR(32) NOT NULL COMMENT '审核阶段',
  `review_status` VARCHAR(32) NOT NULL COMMENT '审核结果',
  `review_comment` VARCHAR(512) DEFAULT NULL COMMENT '审核意见',
  `reviewer_id` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `reviewer_name` VARCHAR(64) DEFAULT NULL COMMENT '审核人姓�?,
  `reviewed_at` DATETIME(3) DEFAULT NULL COMMENT '审核时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_no` (`review_no`),
  KEY `idx_report_stage` (`report_id`,`review_stage`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生审核记录�?;

CREATE TABLE `report_compare_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(32) NOT NULL COMMENT '对比任务�?,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `baseline_report_id` BIGINT NOT NULL COMMENT '基线报告ID',
  `compare_report_id` BIGINT NOT NULL COMMENT '对比报告ID',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待执�?1执行�?2已完�?3失败',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  UNIQUE KEY `uk_compare_pair` (`user_id`,`baseline_report_id`,`compare_report_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历年对比任务�?;

CREATE TABLE `report_compare_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '对比任务ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '指标编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '指标名称',
  `base_value` VARCHAR(256) DEFAULT NULL COMMENT '基线�?,
  `compare_value` VARCHAR(256) DEFAULT NULL COMMENT '对比�?,
  `change_value` DECIMAL(18,4) DEFAULT NULL COMMENT '变化�?,
  `change_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '变化�?,
  `trend` TINYINT NOT NULL DEFAULT 0 COMMENT '趋势�?持平 1上升 2下降',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_item` (`task_id`,`item_code`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历年对比结果�?;

CREATE TABLE `report_indicator_yearly` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `report_id` BIGINT NOT NULL COMMENT '报告ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '指标编码',
  `item_name` VARCHAR(128) NOT NULL COMMENT '指标名称',
  `stat_year` INT NOT NULL COMMENT '统计年份',
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '标准化数�?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `abnormal_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否异常',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_yearly_indicator` (`report_id`,`item_code`),
  KEY `idx_user_item_year` (`user_id`,`item_code`,`stat_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='年度指标标准化表';

CREATE TABLE `indicator_trend_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '对比任务ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '指标编码',
  `trend_tag` VARCHAR(64) NOT NULL COMMENT '趋势标签',
  `trend_direction` TINYINT NOT NULL DEFAULT 0 COMMENT '趋势方向�?持平 1升高 2下降 3波动',
  `turning_year` INT DEFAULT NULL COMMENT '拐点年份',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级',
  `tag_reason` VARCHAR(512) DEFAULT NULL COMMENT '标签原因',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_indicator_tag` (`task_id`,`item_code`),
  KEY `idx_item_code` (`item_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='指标趋势标签�?;

CREATE TABLE `health_risk_score` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '对比任务ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `score_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '总分',
  `score_abnormal` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '异常得分',
  `score_trend` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '趋势得分',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级',
  `score_detail` TEXT COMMENT '评分详情',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_score` (`task_id`),
  KEY `idx_user_risk` (`user_id`,`risk_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='健康风险评分�?;

CREATE TABLE `health_advice_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `advice_no` VARCHAR(32) NOT NULL COMMENT '建议单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `report_id` BIGINT DEFAULT NULL COMMENT '报告ID',
  `compare_task_id` BIGINT DEFAULT NULL COMMENT '对比任务ID',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源类型',
  `advice_type` VARCHAR(32) NOT NULL COMMENT '建议类型',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级',
  `advice_title` VARCHAR(128) NOT NULL COMMENT '建议标题',
  `advice_content` TEXT NOT NULL COMMENT '建议内容',
  `action_suggestion` VARCHAR(256) DEFAULT NULL COMMENT '行动建议',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1有效 0失效',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_advice_no` (`advice_no`),
  KEY `idx_user_risk_created` (`user_id`,`risk_level`,`created_at`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_compare_task_id` (`compare_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='健康建议记录�?;

CREATE TABLE `stat_daily_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `stat_date` DATE NOT NULL COMMENT '统计日期',
  `center_code` VARCHAR(32) NOT NULL COMMENT '体检中心编码',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `appointment_cnt` INT NOT NULL DEFAULT 0 COMMENT '预约�?,
  `completed_cnt` INT NOT NULL DEFAULT 0 COMMENT '完成�?,
  `cancel_cnt` INT NOT NULL DEFAULT 0 COMMENT '取消�?,
  `order_cnt` INT NOT NULL DEFAULT 0 COMMENT '订单�?,
  `pay_success_cnt` INT NOT NULL DEFAULT 0 COMMENT '支付成功�?,
  `refund_cnt` INT NOT NULL DEFAULT 0 COMMENT '退款数',
  `abnormal_report_cnt` INT NOT NULL DEFAULT 0 COMMENT '异常报告�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stat_daily` (`stat_date`,`center_code`,`package_id`),
  KEY `idx_stat_date` (`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运营日报统计�?;

CREATE TABLE `doctor_consultation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consultation_no` VARCHAR(32) NOT NULL COMMENT '��ѯ����',
  `user_id` BIGINT NOT NULL COMMENT '�û�ID',
  `doctor_id` BIGINT DEFAULT NULL COMMENT '����ҽ��ID',
  `doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '����ҽ������',
  `report_id` BIGINT DEFAULT NULL COMMENT '��������ID',
  `report_no` VARCHAR(32) DEFAULT NULL COMMENT '����������',
  `source_type` VARCHAR(32) NOT NULL COMMENT '��Դҳ��',
  `consultation_type` VARCHAR(32) NOT NULL COMMENT '��ѯ����',
  `consultation_title` VARCHAR(128) DEFAULT NULL COMMENT '��ѯ����',
  `consultation_content` TEXT NOT NULL COMMENT '��ѯ����',
  `consultation_status` TINYINT NOT NULL DEFAULT 0 COMMENT '״̬��0������ 1�ѽ��� 2�ѻظ� 3�ѹر�',
  `priority_level` TINYINT NOT NULL DEFAULT 0 COMMENT '���ȼ���0��ͨ 1�Ӽ� 2������',
  `latest_reply_time` DATETIME(3) DEFAULT NULL COMMENT '���»ظ�ʱ��',
  `closed_time` DATETIME(3) DEFAULT NULL COMMENT '�ر�ʱ��',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consultation_no` (`consultation_no`),
  KEY `idx_consultation_user_created` (`user_id`,`created_at`),
  KEY `idx_consultation_report_created` (`report_id`,`created_at`),
  KEY `idx_consultation_doctor_status` (`doctor_id`,`consultation_status`),
  KEY `idx_consultation_status_created` (`consultation_status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ҽ����ѯ����';

CREATE TABLE `doctor_consultation_reply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consultation_id` BIGINT NOT NULL COMMENT '��ѯID',
  `consultation_no` VARCHAR(32) NOT NULL COMMENT '��ѯ����',
  `reply_role` VARCHAR(16) NOT NULL COMMENT '�ظ���ɫ��USER/DOCTOR/SYSTEM',
  `reply_user_id` BIGINT DEFAULT NULL COMMENT '�ظ���ID',
  `reply_user_name` VARCHAR(64) DEFAULT NULL COMMENT '�ظ�������',
  `reply_content` TEXT NOT NULL COMMENT '�ظ�����',
  `attachment_url` VARCHAR(512) DEFAULT NULL COMMENT '������ַ',
  `reply_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '�ظ�ʱ��',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_reply_consultation_time` (`consultation_id`,`reply_time`),
  KEY `idx_reply_consultation_no` (`consultation_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ҽ����ѯ�ظ���';

CREATE TABLE `operation_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `biz_id` VARCHAR(64) NOT NULL COMMENT '业务ID',
  `action` VARCHAR(32) NOT NULL COMMENT '操作动作',
  `operator_id` BIGINT NOT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(64) NOT NULL COMMENT '操作人姓�?,
  `ip` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `before_data` TEXT COMMENT '变更前数�?,
  `after_data` TEXT COMMENT '变更后数�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_biz` (`biz_type`,`biz_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志�?;

CREATE TABLE `data_dictionary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dict_type` VARCHAR(64) NOT NULL COMMENT '字典类型',
  `dict_code` VARCHAR(64) NOT NULL COMMENT '字典编码',
  `dict_name` VARCHAR(128) NOT NULL COMMENT '字典名称',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '排序�?,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type_code` (`dict_type`,`dict_code`),
  KEY `idx_dict_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据字典�?;

CREATE TABLE `notification_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `channel` VARCHAR(32) NOT NULL COMMENT '通知渠道',
  `template_code` VARCHAR(64) NOT NULL COMMENT '模板编码',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `biz_id` VARCHAR(64) NOT NULL COMMENT '业务ID',
  `content` TEXT NOT NULL COMMENT '通知内容',
  `send_status` TINYINT NOT NULL DEFAULT 0 COMMENT '发送状�?,
  `send_at` DATETIME(3) DEFAULT NULL COMMENT '发送时�?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_channel` (`user_id`,`channel`),
  KEY `idx_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知记录�?;
