DROP DATABASE IF EXISTS `xixin_health`;
CREATE DATABASE `xixin_health` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `xixin_health`;

CREATE TABLE `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_no` VARCHAR(32) NOT NULL COMMENT '鐢ㄦ埛缂栧彿',
  `name` VARCHAR(64) NOT NULL COMMENT '濮撳悕',
  `gender` TINYINT NOT NULL DEFAULT 0 COMMENT '鎬у埆锛?鏈煡 1鐢?2濂?,
  `birth_date` DATE DEFAULT NULL COMMENT '鍑虹敓鏃ユ湡',
  `id_type` TINYINT DEFAULT NULL COMMENT '璇佷欢绫诲瀷',
  `id_no` VARCHAR(64) DEFAULT NULL COMMENT '璇佷欢鍙风爜',
  `mobile` VARCHAR(20) NOT NULL COMMENT '鎵嬫満鍙?,
  `email` VARCHAR(128) DEFAULT NULL COMMENT '閭',
  `password_hash` VARCHAR(128) DEFAULT NULL COMMENT '登录密码哈希',
  `address` VARCHAR(256) DEFAULT NULL COMMENT '鍦板潃',
  `emergency_contact` VARCHAR(64) DEFAULT NULL COMMENT '绱ф€ヨ仈绯讳汉',
  `emergency_mobile` VARCHAR(20) DEFAULT NULL COMMENT '绱ф€ヨ仈绯荤數璇?,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1鍚敤 0鍋滅敤',
  `last_login_at` DATETIME(3) DEFAULT NULL COMMENT '鏈€杩戠櫥褰曟椂闂?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_no` (`user_no`),
  UNIQUE KEY `uk_mobile` (`mobile`),
  UNIQUE KEY `uk_id_no` (`id_no`),
  KEY `idx_name_mobile` (`name`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鐢ㄦ埛琛?;

CREATE TABLE `staff_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL COMMENT '后台账号',
  `password_hash` VARCHAR(128) NOT NULL COMMENT '密码哈希',
  `display_name` VARCHAR(64) NOT NULL COMMENT '显示名称',
  `bind_user_id` BIGINT NOT NULL COMMENT '绑定用户ID',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `last_login_at` DATETIME(3) DEFAULT NULL COMMENT '最近登录时间',
  `department_code` VARCHAR(32) DEFAULT NULL COMMENT '科室编码',
  `department_name` VARCHAR(128) DEFAULT NULL COMMENT '科室名称',
  `specialty` VARCHAR(128) DEFAULT NULL COMMENT '专业方向',
  `center_code` VARCHAR(32) DEFAULT NULL COMMENT '中心编码',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_account_username` (`username`),
  KEY `idx_bind_user_id` (`bind_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台账号表';

CREATE TABLE `doctor_department_rel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `doctor_id` BIGINT NOT NULL COMMENT '医生账号ID',
  `department_code` VARCHAR(32) NOT NULL COMMENT '科室编码',
  `department_name` VARCHAR(128) NOT NULL COMMENT '科室名称',
  `center_code` VARCHAR(32) DEFAULT NULL COMMENT '中心编码',
  `is_primary` TINYINT NOT NULL DEFAULT 0 COMMENT '是否主科室',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doctor_department_rel` (`doctor_id`,`department_code`,`center_code`),
  KEY `idx_department_code` (`department_code`),
  KEY `idx_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生科室关系表';

CREATE TABLE `staff_role_rel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `staff_account_id` BIGINT NOT NULL COMMENT '后台账号ID',
  `role_code` VARCHAR(32) NOT NULL COMMENT '角色编码',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_staff_role` (`staff_account_id`,`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台账号角色关联表';

CREATE TABLE `health_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `allergy_history` TEXT COMMENT '杩囨晱鍙?,
  `past_medical_history` TEXT COMMENT '鏃㈠線鐥呭彶',
  `family_history` TEXT COMMENT '瀹舵棌鐥呭彶',
  `medication_history` TEXT COMMENT '鐢ㄨ嵂鍙?,
  `smoking_status` TINYINT NOT NULL DEFAULT 0 COMMENT '鍚哥儫鐘舵€?,
  `drinking_status` TINYINT NOT NULL DEFAULT 0 COMMENT '楗厭鐘舵€?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_profile` (`user_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍋ュ悍妗ｆ琛?;

CREATE TABLE `exam_package` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `package_code` VARCHAR(32) NOT NULL COMMENT '濂楅缂栫爜',
  `package_name` VARCHAR(128) NOT NULL COMMENT '濂楅鍚嶇О',
  `category` VARCHAR(32) DEFAULT NULL COMMENT '濂楅鍒嗙被',
  `price` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '浠锋牸',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1涓婃灦 0涓嬫灦',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_code` (`package_code`),
  KEY `idx_package_name` (`package_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴濂楅琛?;

CREATE TABLE `exam_package_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '妫€鏌ラ」缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '妫€鏌ラ」鍚嶇О',
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '鍗曚綅',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '鍙傝€冭寖鍥?,
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_item` (`package_id`,`item_code`),
  KEY `idx_package_id` (`package_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='濂楅妫€鏌ラ」琛?;

CREATE TABLE `appointment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '棰勭害鍗曞彿',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `appoint_date` DATE NOT NULL COMMENT '棰勭害鏃ユ湡',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '鏃舵缂栫爜',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0寰呯‘璁?1宸茬‘璁?2宸插畬鎴?3宸插彇娑?4鐖界害',
  `cancel_reason` VARCHAR(256) DEFAULT NULL COMMENT '鍙栨秷鍘熷洜',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_appointment_no` (`appointment_no`),
  KEY `idx_user_date` (`user_id`,`appoint_date`),
  KEY `idx_center_date_slot` (`center_code`,`appoint_date`,`time_slot_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='棰勭害琛?;

CREATE TABLE `appointment_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `queue_no` VARCHAR(32) NOT NULL COMMENT '鍊欒ˉ鍗曞彿',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `appoint_date` DATE NOT NULL COMMENT '棰勭害鏃ユ湡',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '鏃舵缂栫爜',
  `priority` INT NOT NULL DEFAULT 0 COMMENT '浼樺厛绾?,
  `queue_status` TINYINT NOT NULL DEFAULT 0 COMMENT '鍊欒ˉ鐘舵€侊細0鎺掗槦涓?1宸茶ˉ浣?2宸插け鏁?3宸插彇娑?,
  `expire_at` DATETIME(3) DEFAULT NULL COMMENT '杩囨湡鏃堕棿',
  `confirmed_at` DATETIME(3) DEFAULT NULL COMMENT '纭鏃堕棿',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_queue_no` (`queue_no`),
  KEY `idx_queue_user_date` (`user_id`,`appoint_date`),
  KEY `idx_queue_center_slot` (`center_code`,`appoint_date`,`time_slot_code`,`queue_status`,`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约候补表';

CREATE TABLE `exam_center` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '中心编码',
  `center_name` VARCHAR(128) NOT NULL COMMENT '中心名称',
  `address` VARCHAR(256) DEFAULT NULL COMMENT '地址',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `business_hours` VARCHAR(128) DEFAULT NULL COMMENT '营业时间',
  `description` TEXT DEFAULT NULL COMMENT '中心介绍',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_center_code` (`center_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体检中心表';

CREATE TABLE `resource_capacity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `appoint_date` DATE NOT NULL COMMENT '棰勭害鏃ユ湡',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '鏃舵缂栫爜',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '璧勬簮绫诲瀷',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '璧勬簮缂栫爜',
  `capacity_total` INT NOT NULL DEFAULT 0 COMMENT '鎬诲閲?,
  `capacity_used` INT NOT NULL DEFAULT 0 COMMENT '宸茬敤瀹归噺',
  `capacity_locked` INT NOT NULL DEFAULT 0 COMMENT '閿佸畾瀹归噺',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  `version_no` INT NOT NULL DEFAULT 0 COMMENT '鐗堟湰鍙?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resource_capacity` (`center_code`,`appoint_date`,`time_slot_code`,`resource_type`,`resource_code`),
  KEY `idx_capacity_slot` (`center_code`,`appoint_date`,`time_slot_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璧勬簮瀹归噺琛?;

CREATE TABLE `resource_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `snapshot_no` VARCHAR(32) NOT NULL COMMENT '蹇収鍙?,
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '棰勭害鍗曞彿',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `appoint_date` DATE NOT NULL COMMENT '棰勭害鏃ユ湡',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '鏃舵缂栫爜',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '璧勬簮绫诲瀷',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '璧勬簮缂栫爜',
  `version_no` INT NOT NULL DEFAULT 0 COMMENT '鐗堟湰鍙?,
  `lock_result` TINYINT NOT NULL DEFAULT 0 COMMENT '閿佸畾缁撴灉',
  `snapshot_data` TEXT COMMENT '蹇収鏁版嵁',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_no` (`snapshot_no`),
  KEY `idx_snapshot_appointment` (`appointment_no`),
  KEY `idx_snapshot_slot` (`center_code`,`appoint_date`,`time_slot_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璧勬簮蹇収琛?;

CREATE TABLE `schedule_resource_bind` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `time_slot_code` VARCHAR(32) NOT NULL COMMENT '鏃舵缂栫爜',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '妫€鏌ラ」缂栫爜',
  `resource_type` VARCHAR(32) NOT NULL COMMENT '璧勬簮绫诲瀷',
  `resource_code` VARCHAR(64) NOT NULL COMMENT '璧勬簮缂栫爜',
  `resource_name` VARCHAR(128) DEFAULT NULL COMMENT '璧勬簮鍚嶇О',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1鍚敤 0鍋滅敤',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_schedule_resource_bind` (`center_code`,`time_slot_code`,`package_id`,`item_code`,`resource_type`,`resource_code`),
  KEY `idx_bind_package` (`package_id`,`item_code`),
  KEY `idx_bind_resource` (`center_code`,`time_slot_code`,`resource_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鏃舵璧勬簮缁戝畾琛?;

CREATE TABLE `order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(32) NOT NULL COMMENT '璁㈠崟鍙?,
  `appointment_id` BIGINT NOT NULL COMMENT '棰勭害ID',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '鎬婚噾棰?,
  `pay_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '瀹炰粯閲戦',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '浼樻儬閲戦',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0寰呮敮浠?1宸叉敮浠?2宸查€€娆?3閮ㄥ垎閫€娆?4宸插畬鎴?5宸插叧闂?,
  `pay_channel` VARCHAR(32) DEFAULT NULL COMMENT '鏀粯娓犻亾',
  `pay_time` DATETIME(3) DEFAULT NULL COMMENT '鏀粯鏃堕棿',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  UNIQUE KEY `uk_appointment_id` (`appointment_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璁㈠崟琛?;

CREATE TABLE `order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `item_type` TINYINT NOT NULL DEFAULT 0 COMMENT '绫诲瀷锛?濂楅椤?1闄勫姞椤?,
  `ref_item_code` VARCHAR(32) NOT NULL COMMENT '鍏宠仈椤圭紪鐮?,
  `ref_item_name` VARCHAR(128) NOT NULL COMMENT '鍏宠仈椤瑰悕绉?,
  `qty` INT NOT NULL DEFAULT 1 COMMENT '鏁伴噺',
  `unit_price` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '鍗曚环',
  `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '閲戦',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_ref_item` (`order_id`,`ref_item_code`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璁㈠崟鏄庣粏琛?;

CREATE TABLE `order_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '璁㈠崟鍙?,
  `snapshot_type` VARCHAR(32) NOT NULL COMMENT '蹇収绫诲瀷',
  `snapshot_content` TEXT NOT NULL COMMENT '蹇収鍐呭',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order_snapshot` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璁㈠崟蹇収琛?;

CREATE TABLE `order_settlement_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `order_item_id` BIGINT NOT NULL COMMENT '璁㈠崟椤笽D',
  `settlement_type` VARCHAR(32) NOT NULL COMMENT '缁撶畻绫诲瀷',
  `origin_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '鍘熷閲戦',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '浼樻儬鍒嗘憡閲戦',
  `settlement_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '缁撶畻閲戦',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order_item` (`order_id`,`order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璁㈠崟缁撶畻鏄庣粏琛?;

CREATE TABLE `payment_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `payment_no` VARCHAR(32) NOT NULL COMMENT '支付流水号',
  `order_no` VARCHAR(32) NOT NULL COMMENT '订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `pay_method` VARCHAR(32) NOT NULL COMMENT '支付方式',
  `pay_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '支付金额',
  `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待支付 1成功 2失败',
  `pay_time` DATETIME(3) DEFAULT NULL COMMENT '支付时间',
  `third_party_no` VARCHAR(64) DEFAULT NULL COMMENT '第三方交易号',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_no` (`payment_no`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鏀粯娴佹按琛?;

CREATE TABLE `refund_apply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apply_no` VARCHAR(32) NOT NULL COMMENT '閫€娆剧敵璇峰崟鍙?,
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '璁㈠崟鍙?,
  `refund_type` VARCHAR(32) NOT NULL COMMENT '閫€娆剧被鍨?,
  `apply_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '鐢宠閫€娆鹃噾棰?,
  `reason` VARCHAR(256) DEFAULT NULL COMMENT '鐢宠鍘熷洜',
  `apply_status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐢宠鐘舵€侊細0寰呭鏍?1瀹℃牳閫氳繃 2瀹℃牳鎷掔粷 3閫€娆句腑 4宸插畬鎴?,
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '瀹℃牳鐘舵€?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_refund_apply_order` (`order_id`,`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='閫€娆剧敵璇疯〃';

CREATE TABLE `refund_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_apply_id` BIGINT NOT NULL COMMENT '閫€娆剧敵璇稩D',
  `apply_no` VARCHAR(32) NOT NULL COMMENT '閫€娆剧敵璇峰崟鍙?,
  `audit_action` VARCHAR(32) NOT NULL COMMENT '瀹℃牳鍔ㄤ綔',
  `audit_result` VARCHAR(32) NOT NULL COMMENT '瀹℃牳缁撴灉',
  `audit_remark` VARCHAR(512) DEFAULT NULL COMMENT '瀹℃牳澶囨敞',
  `operator_id` BIGINT DEFAULT NULL COMMENT '鎿嶄綔浜篒D',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '鎿嶄綔浜哄鍚?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_refund_apply_id` (`refund_apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='閫€娆惧鏍告棩蹇楄〃';

CREATE TABLE `refund_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_no` VARCHAR(32) NOT NULL COMMENT '閫€娆炬祦姘村彿',
  `refund_apply_id` BIGINT NOT NULL COMMENT '閫€娆剧敵璇稩D',
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '璁㈠崟鍙?,
  `channel` VARCHAR(32) NOT NULL COMMENT '閫€娆炬笭閬?,
  `channel_refund_no` VARCHAR(64) DEFAULT NULL COMMENT '娓犻亾閫€娆惧崟鍙?,
  `refund_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '閫€娆鹃噾棰?,
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0澶勭悊涓?1鎴愬姛 2澶辫触',
  `refund_time` DATETIME(3) DEFAULT NULL COMMENT '閫€娆炬椂闂?,
  `raw_payload` TEXT COMMENT '鍘熷杩斿洖鏁版嵁',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no` (`refund_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_refund_apply_id` (`refund_apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='閫€娆炬墽琛岀粨鏋滆〃';

CREATE TABLE `exam_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(32) NOT NULL COMMENT '浣撴浠诲姟鍙?,
  `appointment_id` BIGINT NOT NULL COMMENT '棰勭害ID',
  `appointment_no` VARCHAR(32) NOT NULL COMMENT '棰勭害鍗曞彿',
  `order_id` BIGINT NOT NULL COMMENT '璁㈠崟ID',
  `order_no` VARCHAR(32) NOT NULL COMMENT '璁㈠崟鍙?,
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `task_date` DATE NOT NULL COMMENT '浣撴鏃ユ湡',
  `task_status` TINYINT NOT NULL DEFAULT 0 COMMENT '浠诲姟鐘舵€侊細0寰呭埌闄?1杩涜涓?2宸插畬鎴?3宸插彇娑?,
  `report_status` TINYINT NOT NULL DEFAULT 0 COMMENT '鎶ュ憡鐘舵€侊細0鏈敓鎴?1鐢熸垚涓?2寰呭鏍?3宸插彂甯?,
  `guide_status` TINYINT NOT NULL DEFAULT 0 COMMENT '瀵兼鐘舵€侊細0鏈紑濮?1杩涜涓?2宸插畬鎴?,
  `arrive_time` DATETIME(3) DEFAULT NULL COMMENT '鍒伴櫌鏃堕棿',
  `start_time` DATETIME(3) DEFAULT NULL COMMENT '寮€濮嬫椂闂?,
  `complete_time` DATETIME(3) DEFAULT NULL COMMENT '瀹屾垚鏃堕棿',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  UNIQUE KEY `uk_exam_task_appointment_id` (`appointment_id`),
  KEY `idx_exam_task_user_status` (`user_id`,`task_status`),
  KEY `idx_exam_task_center_date` (`center_code`,`task_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴浠诲姟琛?;

CREATE TABLE `exam_department_route` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `route_code` VARCHAR(32) NOT NULL COMMENT '瀵兼璺嚎缂栫爜',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '妫€鏌ラ」缂栫爜',
  `department_code` VARCHAR(32) NOT NULL COMMENT '绉戝缂栫爜',
  `department_name` VARCHAR(128) NOT NULL COMMENT '绉戝鍚嶇О',
  `room_no` VARCHAR(64) DEFAULT NULL COMMENT '鎴块棿鍙?,
  `floor_no` VARCHAR(32) DEFAULT NULL COMMENT '妤煎眰',
  `building_no` VARCHAR(32) DEFAULT NULL COMMENT '妤兼爧',
  `route_sort` INT NOT NULL DEFAULT 0 COMMENT '璺嚎椤哄簭',
  `guide_text` VARCHAR(512) DEFAULT NULL COMMENT '瀵兼鎻愮ず',
  `need_empty_stomach` TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁绌鸿吂',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1鍚敤 0鍋滅敤',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_code` (`route_code`),
  UNIQUE KEY `uk_route_package_item` (`center_code`,`package_id`,`item_code`),
  KEY `idx_route_center_package` (`center_code`,`package_id`,`route_sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='瀵兼璺嚎琛?;

CREATE TABLE `exam_task_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_item_no` VARCHAR(32) NOT NULL COMMENT '浠诲姟椤瑰彿',
  `task_id` BIGINT NOT NULL COMMENT '浠诲姟ID',
  `task_no` VARCHAR(32) NOT NULL COMMENT '浠诲姟鍙?,
  `item_code` VARCHAR(32) NOT NULL COMMENT '妫€鏌ラ」缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '妫€鏌ラ」鍚嶇О',
  `department_code` VARCHAR(32) NOT NULL COMMENT '绉戝缂栫爜',
  `department_name` VARCHAR(128) NOT NULL COMMENT '绉戝鍚嶇О',
  `doctor_id` BIGINT DEFAULT NULL COMMENT '鍖荤敓ID',
  `doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '鍖荤敓濮撳悕',
  `room_no` VARCHAR(64) DEFAULT NULL COMMENT '鎴块棿鍙?,
  `route_sort` INT NOT NULL DEFAULT 0 COMMENT '璺嚎椤哄簭',
  `item_status` TINYINT NOT NULL DEFAULT 0 COMMENT '椤圭洰鐘舵€侊細0寰呮鏌?1妫€鏌ヤ腑 2宸插畬鎴?3宸茶烦杩?4闇€澶嶆',
  `entry_status` TINYINT NOT NULL DEFAULT 0 COMMENT '褰曞叆鐘舵€侊細0鏈綍鍏?1宸叉殏瀛?2宸叉彁浜?,
  `start_time` DATETIME(3) DEFAULT NULL COMMENT '寮€濮嬫椂闂?,
  `complete_time` DATETIME(3) DEFAULT NULL COMMENT '瀹屾垚鏃堕棿',
  `skip_reason` VARCHAR(256) DEFAULT NULL COMMENT '璺宠繃鍘熷洜',
  `remark` VARCHAR(256) DEFAULT NULL COMMENT '澶囨敞',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_item_no` (`task_item_no`),
  UNIQUE KEY `uk_task_item_unique` (`task_id`,`item_code`),
  KEY `idx_task_route` (`task_id`,`route_sort`),
  KEY `idx_doctor_status` (`doctor_id`,`item_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴浠诲姟椤硅〃';

CREATE TABLE `exam_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `result_no` VARCHAR(32) NOT NULL COMMENT '缁撴灉鍙?,
  `task_id` BIGINT NOT NULL COMMENT '浠诲姟ID',
  `task_item_id` BIGINT NOT NULL COMMENT '浠诲姟椤笽D',
  `task_item_no` VARCHAR(32) NOT NULL COMMENT '浠诲姟椤瑰彿',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `report_id` BIGINT DEFAULT NULL COMMENT '鎶ュ憡ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '妫€鏌ラ」缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '妫€鏌ラ」鍚嶇О',
  `result_type` VARCHAR(32) NOT NULL COMMENT '缁撴灉绫诲瀷',
  `result_value` VARCHAR(256) DEFAULT NULL COMMENT '缁撴灉鏂囨湰鍊?,
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '缁撴灉鏁板€?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '鍗曚綅',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '鍙傝€冭寖鍥?,
  `conclusion` VARCHAR(512) DEFAULT NULL COMMENT '妫€鏌ョ粨璁?,
  `is_abnormal` TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁寮傚父',
  `abnormal_level` TINYINT NOT NULL DEFAULT 0 COMMENT '寮傚父绾у埆',
  `entry_doctor_id` BIGINT DEFAULT NULL COMMENT '褰曞叆鍖荤敓ID',
  `entry_doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '褰曞叆鍖荤敓濮撳悕',
  `entry_time` DATETIME(3) DEFAULT NULL COMMENT '褰曞叆鏃堕棿',
  `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '瀹℃牳鐘舵€侊細0鏈鏍?1宸插鏍?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_result_no` (`result_no`),
  KEY `idx_result_task_item` (`task_item_id`),
  KEY `idx_result_user_item` (`user_id`,`item_code`),
  KEY `idx_result_report_id` (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴缁撴灉琛?;

CREATE TABLE `exam_result_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `attachment_no` VARCHAR(32) NOT NULL COMMENT '闄勪欢鍙?,
  `result_id` BIGINT NOT NULL COMMENT '缁撴灉ID',
  `task_item_id` BIGINT NOT NULL COMMENT '浠诲姟椤笽D',
  `file_name` VARCHAR(256) NOT NULL COMMENT '鏂囦欢鍚?,
  `file_url` VARCHAR(512) NOT NULL COMMENT '鏂囦欢鍦板潃',
  `file_type` VARCHAR(64) DEFAULT NULL COMMENT '鏂囦欢绫诲瀷',
  `file_size` BIGINT DEFAULT NULL COMMENT '鏂囦欢澶у皬',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_attachment_no` (`attachment_no`),
  KEY `idx_result_id` (`result_id`),
  KEY `idx_task_item_id` (`task_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴缁撴灉闄勪欢琛?;

CREATE TABLE `report_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `template_code` VARCHAR(32) NOT NULL COMMENT '妯℃澘缂栫爜',
  `template_name` VARCHAR(128) NOT NULL COMMENT '妯℃澘鍚嶇О',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `template_type` VARCHAR(32) NOT NULL COMMENT '妯℃澘绫诲瀷',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '鐗堟湰鍙?,
  `render_engine` VARCHAR(32) DEFAULT NULL COMMENT '娓叉煋寮曟搸',
  `template_config` TEXT COMMENT '妯℃澘閰嶇疆',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1鍚敤 0鍋滅敤',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_code` (`template_code`),
  KEY `idx_package_status` (`package_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎶ュ憡妯℃澘琛?;

CREATE TABLE `report_section_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `template_id` BIGINT NOT NULL COMMENT '妯℃澘ID',
  `section_code` VARCHAR(32) NOT NULL COMMENT '绔犺妭缂栫爜',
  `section_name` VARCHAR(128) NOT NULL COMMENT '绔犺妭鍚嶇О',
  `section_type` VARCHAR(32) NOT NULL COMMENT '绔犺妭绫诲瀷',
  `data_source_type` VARCHAR(32) NOT NULL COMMENT '鏁版嵁鏉ユ簮绫诲瀷',
  `item_codes` TEXT COMMENT '鎸囨爣缂栫爜闆嗗悎',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?,
  `render_rule` TEXT COMMENT '娓叉煋瑙勫垯',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_section` (`template_id`,`section_code`),
  KEY `idx_template_sort` (`template_id`,`sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎶ュ憡妯℃澘绔犺妭琛?;

CREATE TABLE `exam_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_no` VARCHAR(32) NOT NULL COMMENT '鎶ュ憡缂栧彿',
  `appointment_id` BIGINT NOT NULL COMMENT '棰勭害ID',
  `task_id` BIGINT NOT NULL COMMENT '浣撴浠诲姟ID',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `template_id` BIGINT DEFAULT NULL COMMENT '妯℃澘ID',
  `report_date` DATE NOT NULL COMMENT '鎶ュ憡鏃ユ湡',
  `overall_conclusion` TEXT COMMENT '鎬讳綋缁撹',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0鐢熸垚涓?1寰呭鏍?2宸插鏍?3宸插彂甯?4宸叉挙鍥?,
  `pdf_url` VARCHAR(512) DEFAULT NULL COMMENT 'PDF鍦板潃',
  `pdf_object_key` VARCHAR(512) DEFAULT NULL COMMENT 'PDF对象存储Key',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '鐗堟湰鍙?,
  `published_at` DATETIME(3) DEFAULT NULL COMMENT '鍙戝竷鏃堕棿',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`),
  UNIQUE KEY `uk_exam_report_appointment_id` (`appointment_id`),
  UNIQUE KEY `uk_exam_report_task_id` (`task_id`),
  KEY `idx_user_report_date` (`user_id`,`report_date`),
  KEY `idx_report_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='浣撴鎶ュ憡琛?;

CREATE TABLE `exam_report_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_id` BIGINT NOT NULL COMMENT '鎶ュ憡ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '鎸囨爣缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '鎸囨爣鍚嶇О',
  `result_value` VARCHAR(256) DEFAULT NULL COMMENT '缁撴灉鍊?,
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '缁撴灉鏁板€?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '鍗曚綅',
  `ref_range` VARCHAR(128) DEFAULT NULL COMMENT '鍙傝€冭寖鍥?,
  `is_abnormal` TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁寮傚父',
  `abnormal_level` TINYINT NOT NULL DEFAULT 0 COMMENT '寮傚父绾у埆',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_item` (`report_id`,`item_code`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_item_code` (`item_code`),
  KEY `idx_abnormal` (`is_abnormal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎶ュ憡鎸囨爣琛?;

CREATE TABLE `exam_report_item_abnormal` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `report_id` BIGINT NOT NULL COMMENT '鎶ュ憡ID',
  `report_item_id` BIGINT NOT NULL COMMENT '鎶ュ憡鎸囨爣ID',
  `abnormal_code` VARCHAR(32) NOT NULL COMMENT '寮傚父缂栫爜',
  `abnormal_name` VARCHAR(128) NOT NULL COMMENT '寮傚父鍚嶇О',
  `abnormal_level` TINYINT NOT NULL DEFAULT 1 COMMENT '寮傚父绾у埆',
  `suggestion` VARCHAR(512) DEFAULT NULL COMMENT '寤鸿',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0寰呰窡杩?1宸茶窡杩?2宸插拷鐣?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_item_abnormal` (`report_item_id`,`abnormal_code`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_level_status` (`abnormal_level`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎶ュ憡寮傚父椤硅〃';

CREATE TABLE `doctor_review_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_no` VARCHAR(32) NOT NULL COMMENT '瀹℃牳娴佹按鍙?,
  `report_id` BIGINT NOT NULL COMMENT '鎶ュ憡ID',
  `task_id` BIGINT NOT NULL COMMENT '浣撴浠诲姟ID',
  `review_stage` VARCHAR(32) NOT NULL COMMENT '瀹℃牳闃舵',
  `review_status` VARCHAR(32) NOT NULL COMMENT '瀹℃牳缁撴灉',
  `review_comment` VARCHAR(512) DEFAULT NULL COMMENT '瀹℃牳鎰忚',
  `reviewer_id` BIGINT DEFAULT NULL COMMENT '瀹℃牳浜篒D',
  `reviewer_name` VARCHAR(64) DEFAULT NULL COMMENT '瀹℃牳浜哄鍚?,
  `reviewed_at` DATETIME(3) DEFAULT NULL COMMENT '瀹℃牳鏃堕棿',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_no` (`review_no`),
  KEY `idx_report_stage` (`report_id`,`review_stage`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍖荤敓瀹℃牳璁板綍琛?;

CREATE TABLE `report_compare_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(32) NOT NULL COMMENT '瀵规瘮浠诲姟鍙?,
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `baseline_report_id` BIGINT NOT NULL COMMENT '鍩虹嚎鎶ュ憡ID',
  `compare_report_id` BIGINT NOT NULL COMMENT '瀵规瘮鎶ュ憡ID',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '鐘舵€侊細0寰呮墽琛?1鎵ц涓?2宸插畬鎴?3澶辫触',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  UNIQUE KEY `uk_compare_pair` (`user_id`,`baseline_report_id`,`compare_report_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍘嗗勾瀵规瘮浠诲姟琛?;

CREATE TABLE `report_compare_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '瀵规瘮浠诲姟ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '鎸囨爣缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '鎸囨爣鍚嶇О',
  `base_value` VARCHAR(256) DEFAULT NULL COMMENT '鍩虹嚎鍊?,
  `compare_value` VARCHAR(256) DEFAULT NULL COMMENT '瀵规瘮鍊?,
  `change_value` DECIMAL(18,4) DEFAULT NULL COMMENT '鍙樺寲鍊?,
  `change_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '鍙樺寲鐜?,
  `trend` TINYINT NOT NULL DEFAULT 0 COMMENT '瓒嬪娍锛?鎸佸钩 1涓婂崌 2涓嬮檷',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_item` (`task_id`,`item_code`),
  KEY `idx_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍘嗗勾瀵规瘮缁撴灉琛?;

CREATE TABLE `report_indicator_yearly` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `report_id` BIGINT NOT NULL COMMENT '鎶ュ憡ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '鎸囨爣缂栫爜',
  `item_name` VARCHAR(128) NOT NULL COMMENT '鎸囨爣鍚嶇О',
  `stat_year` INT NOT NULL COMMENT '缁熻骞翠唤',
  `result_number` DECIMAL(18,4) DEFAULT NULL COMMENT '鏍囧噯鍖栨暟鍊?,
  `unit` VARCHAR(32) DEFAULT NULL COMMENT '鍗曚綅',
  `abnormal_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁寮傚父',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_yearly_indicator` (`report_id`,`item_code`),
  KEY `idx_user_item_year` (`user_id`,`item_code`,`stat_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='骞村害鎸囨爣鏍囧噯鍖栬〃';

CREATE TABLE `indicator_trend_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '瀵规瘮浠诲姟ID',
  `item_code` VARCHAR(32) NOT NULL COMMENT '鎸囨爣缂栫爜',
  `trend_tag` VARCHAR(64) NOT NULL COMMENT '瓒嬪娍鏍囩',
  `trend_direction` TINYINT NOT NULL DEFAULT 0 COMMENT '瓒嬪娍鏂瑰悜锛?鎸佸钩 1鍗囬珮 2涓嬮檷 3娉㈠姩',
  `turning_year` INT DEFAULT NULL COMMENT '鎷愮偣骞翠唤',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '椋庨櫓绛夌骇',
  `tag_reason` VARCHAR(512) DEFAULT NULL COMMENT '鏍囩鍘熷洜',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_indicator_tag` (`task_id`,`item_code`),
  KEY `idx_item_code` (`item_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎸囨爣瓒嬪娍鏍囩琛?;

CREATE TABLE `health_risk_score` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL COMMENT '瀵规瘮浠诲姟ID',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `score_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '鎬诲垎',
  `score_abnormal` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '寮傚父寰楀垎',
  `score_trend` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '瓒嬪娍寰楀垎',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '椋庨櫓绛夌骇',
  `score_detail` TEXT COMMENT '璇勫垎璇︽儏',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_score` (`task_id`),
  KEY `idx_user_risk` (`user_id`,`risk_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍋ュ悍椋庨櫓璇勫垎琛?;

CREATE TABLE `health_advice_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `advice_no` VARCHAR(32) NOT NULL COMMENT '寤鸿鍗曞彿',
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `report_id` BIGINT DEFAULT NULL COMMENT '鎶ュ憡ID',
  `compare_task_id` BIGINT DEFAULT NULL COMMENT '瀵规瘮浠诲姟ID',
  `source_type` VARCHAR(32) NOT NULL COMMENT '鏉ユ簮绫诲瀷',
  `advice_type` VARCHAR(32) NOT NULL COMMENT '寤鸿绫诲瀷',
  `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '椋庨櫓绛夌骇',
  `advice_title` VARCHAR(128) NOT NULL COMMENT '寤鸿鏍囬',
  `advice_content` TEXT NOT NULL COMMENT '寤鸿鍐呭',
  `action_suggestion` VARCHAR(256) DEFAULT NULL COMMENT '琛屽姩寤鸿',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€侊細1鏈夋晥 0澶辨晥',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_advice_no` (`advice_no`),
  KEY `idx_user_risk_created` (`user_id`,`risk_level`,`created_at`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_compare_task_id` (`compare_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍋ュ悍寤鸿璁板綍琛?;

CREATE TABLE `stat_daily_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `stat_date` DATE NOT NULL COMMENT '缁熻鏃ユ湡',
  `center_code` VARCHAR(32) NOT NULL COMMENT '浣撴涓績缂栫爜',
  `package_id` BIGINT NOT NULL COMMENT '濂楅ID',
  `appointment_cnt` INT NOT NULL DEFAULT 0 COMMENT '棰勭害鏁?,
  `completed_cnt` INT NOT NULL DEFAULT 0 COMMENT '瀹屾垚鏁?,
  `cancel_cnt` INT NOT NULL DEFAULT 0 COMMENT '鍙栨秷鏁?,
  `order_cnt` INT NOT NULL DEFAULT 0 COMMENT '璁㈠崟鏁?,
  `pay_success_cnt` INT NOT NULL DEFAULT 0 COMMENT '鏀粯鎴愬姛鏁?,
  `refund_cnt` INT NOT NULL DEFAULT 0 COMMENT '閫€娆炬暟',
  `abnormal_report_cnt` INT NOT NULL DEFAULT 0 COMMENT '寮傚父鎶ュ憡鏁?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stat_daily` (`stat_date`,`center_code`,`package_id`),
  KEY `idx_stat_date` (`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='杩愯惀鏃ユ姤缁熻琛?;

CREATE TABLE `doctor_consultation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consultation_no` VARCHAR(32) NOT NULL COMMENT '咨询单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `doctor_id` BIGINT DEFAULT NULL COMMENT '接诊医生ID',
  `doctor_name` VARCHAR(64) DEFAULT NULL COMMENT '接诊医生姓名',
  `report_id` BIGINT DEFAULT NULL COMMENT '关联报告ID',
  `report_no` VARCHAR(32) DEFAULT NULL COMMENT '关联报告编号',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源页面',
  `consultation_type` VARCHAR(32) NOT NULL COMMENT '咨询类型',
  `consultation_title` VARCHAR(128) DEFAULT NULL COMMENT '咨询标题',
  `consultation_content` TEXT NOT NULL COMMENT '咨询内容',
  `consultation_status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0待接诊 1已接诊 2已回复 3已关闭',
  `priority_level` TINYINT NOT NULL DEFAULT 0 COMMENT '优先级：0普通 1加急 2高优先',
  `latest_reply_time` DATETIME(3) DEFAULT NULL COMMENT '最新回复时间',
  `closed_time` DATETIME(3) DEFAULT NULL COMMENT '关闭时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consultation_no` (`consultation_no`),
  KEY `idx_consultation_user_created` (`user_id`,`created_at`),
  KEY `idx_consultation_report_created` (`report_id`,`created_at`),
  KEY `idx_consultation_doctor_status` (`doctor_id`,`consultation_status`),
  KEY `idx_consultation_status_created` (`consultation_status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生咨询主表';

CREATE TABLE `doctor_consultation_reply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consultation_id` BIGINT NOT NULL COMMENT '咨询ID',
  `consultation_no` VARCHAR(32) NOT NULL COMMENT '咨询单号',
  `reply_role` VARCHAR(16) NOT NULL COMMENT '回复角色：USER/DOCTOR/SYSTEM',
  `reply_user_id` BIGINT DEFAULT NULL COMMENT '回复人ID',
  `reply_user_name` VARCHAR(64) DEFAULT NULL COMMENT '回复人姓名',
  `reply_content` TEXT NOT NULL COMMENT '回复内容',
  `attachment_url` VARCHAR(512) DEFAULT NULL COMMENT '附件地址',
  `message_type` VARCHAR(32) DEFAULT 'TEXT' COMMENT '消息类型：TEXT/REPORT_PDF',
  `ref_report_no` VARCHAR(32) DEFAULT NULL COMMENT '引用报告编号',
  `reply_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '回复时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_reply_consultation_time` (`consultation_id`,`reply_time`),
  KEY `idx_reply_consultation_no` (`consultation_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生咨询回复表';

CREATE TABLE `operation_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `biz_type` VARCHAR(32) NOT NULL COMMENT '涓氬姟绫诲瀷',
  `biz_id` VARCHAR(64) NOT NULL COMMENT '涓氬姟ID',
  `action` VARCHAR(32) NOT NULL COMMENT '鎿嶄綔鍔ㄤ綔',
  `operator_id` BIGINT NOT NULL COMMENT '鎿嶄綔浜篒D',
  `operator_name` VARCHAR(64) NOT NULL COMMENT '鎿嶄綔浜哄鍚?,
  `ip` VARCHAR(64) DEFAULT NULL COMMENT 'IP鍦板潃',
  `before_data` TEXT COMMENT '鍙樻洿鍓嶆暟鎹?,
  `after_data` TEXT COMMENT '鍙樻洿鍚庢暟鎹?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_biz` (`biz_type`,`biz_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鎿嶄綔鏃ュ織琛?;

CREATE TABLE `data_dictionary` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dict_type` VARCHAR(64) NOT NULL COMMENT '瀛楀吀绫诲瀷',
  `dict_code` VARCHAR(64) NOT NULL COMMENT '瀛楀吀缂栫爜',
  `dict_name` VARCHAR(128) NOT NULL COMMENT '瀛楀吀鍚嶇О',
  `sort_no` INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?,
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type_code` (`dict_type`,`dict_code`),
  KEY `idx_dict_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鏁版嵁瀛楀吀琛?;

CREATE TABLE `notification_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '鐢ㄦ埛ID',
  `channel` VARCHAR(32) NOT NULL COMMENT '閫氱煡娓犻亾',
  `template_code` VARCHAR(64) NOT NULL COMMENT '妯℃澘缂栫爜',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '涓氬姟绫诲瀷',
  `biz_id` VARCHAR(64) NOT NULL COMMENT '涓氬姟ID',
  `content` TEXT NOT NULL COMMENT '閫氱煡鍐呭',
  `send_status` TINYINT NOT NULL DEFAULT 0 COMMENT '鍙戦€佺姸鎬?,
  `send_at` DATETIME(3) DEFAULT NULL COMMENT '鍙戦€佹椂闂?,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_by` BIGINT DEFAULT NULL,
  `updated_by` BIGINT DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_channel` (`user_id`,`channel`),
  KEY `idx_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='閫氱煡璁板綍琛?;
